from app.models import db, Plant, environment, SCHEMA


# Adds a demo user, you can add other users here if you want
def seed_plants():
    plant1 = Plant(name= "3 Pack of Ionantha Guatemala Air Plants - 30 Day Air Plant Guarantee - Spectacular Blooms - Air Plants for Sale - FAST SHIPPING", price= 4.95, details= "Ionantha Guatemala produces brilliant green, yellow, orange, red and purple blooming colors. They also grow the cutest 'pups' from their base that you will fall in love with! You can separate them as they grow or let them grow into a large ball of air plant beauty. They are perfect for glass globes, small containers, and terrariums!", preview_image_url= 'https://i.etsystatic.com/6916338/r/il/8583dd/1332210138/il_794xN.1332210138_fkv8.jpg', user_id= 1 )
    plant2 = Plant(name= "Giant Monstera Deliciosa | Swiss Cheese Plant | The Perfect Trendy Plant", price= 34.99, details= "Monstera Deliciosa, or the Swiss Cheese Plant, has quickly become one of the trendiest house plants in recent years. These plants add a stylish look to any room, and are exceptionally easy to care for as far as foliage plants go. " , preview_image_url= "https://i.etsystatic.com/18193121/r/il/df7c73/2191089335/il_794xN.2191089335_n3d5.jpg", user_id=1 )
    plant3 = Plant(name= "Fresh Eucalyptus Shower Bundle, Indoor Shower Plants, Fresh Eucalyptus Plant, Easy Plants, Boho Decor, Plant Lady, Live Eucalyptus Plants", price= 13.44, details= "Reimagine your showers with our eucalyptus shower plants! Our fresh eucalyptus shower bundle comes cut, wrapped and tied with a self adhesive hook to put exactly where you want it in your shower. Steam releases the aromas of your fresh eucalyptus to make showers more relaxing, enjoyable, and spa-like.", preview_image_url= "https://i.etsystatic.com/22078381/r/il/93c194/4053466003/il_794xN.4053466003_noi9.jpg" , user_id=1 )
    plant4 = Plant(name= "Callisia Repens Pink Lady | Callisia Repens Pink Panther | Bolivian Jew Plant | Turtle Vine | Creeping Inch Plant | Pink Plant | Pink Beauty", price= 11.89, details= "The Callisia Repens Pink Lady are Beautiful Pink Plants that Grows Very Full and Lush. Also known as many other names, such as Pink Panther - Bolivian Jew Plant - Turtle Vine they appear like Mini Tradescantia Bubblegum", preview_image_url= 'https://i.etsystatic.com/24205493/r/il/89604f/4249594526/il_794xN.4249594526_bolp.jpg', user_id=2 )
    plant5 = Plant(name= "12 potted succulents plant collection | housewarming decor plants | wedding favors potted plants | real succulent for crafts", price= 27.74, details= "12 different Succulent Plants including cactus. Plant collection for wedding crafts favors, for best friend gifts or just a housewarmings gift for home. Succulent plant collections gift box. Plant craft supply for projects like terrarium, vertical planters, wedding favors and more.", preview_image_url= "https://i.etsystatic.com/21450930/r/il/eecd07/3312099260/il_340x270.3312099260_1spd.jpg", user_id=2 )
    plant6 = Plant(name= "The Great Deku Tree Planter - 3D Printed Hand-Painted Succulent Planter", price= 39.99, details= "The perfect succulent planter for a Legend of Zelda lover, now available for your desk or shelf. This item is meticulously modeled to include as much detail as possible, 3D printed in woodfill PLA plastic, and stained with water-based wood stain. It measures 8 inches wide, 7 inches deep, and 4 inches tall. The planting area is roughly 2.5 inches deep and 2.5 inches in diameter, making this planter perfect for mini succulents or air plants, or even colored sand/rocks, but not larger plants. Does not have a drainage hole, but one can be added upon request. Mini-succulents pictured are not included. Each one of our statues is textured and painted by hand, which means each one is completely unique and will vary slightly (the planter may be lighter or darker in tone due to differences in stain). Free shipping on domestic orders only.", preview_image_url= "https://i.etsystatic.com/7795802/r/il/b2d3eb/4026937965/il_794xN.4026937965_7zsu.jpg", user_id=3 )
    plant7 = Plant(name= "Korok - Plant Pot Decoration - Breath of the Wild", price= 2.99, details= "Flying Korok! To celebrate the release of Breath of the Wild and the return of the Koroks, Our store has created a flying korok designed to brighten up your flower display! After the annual ceremony in the Forest Haven, Koroks fly off to distant parts of the world to sow tree seeds and raise new patches of forest.", preview_image_url= "https://i.etsystatic.com/13356203/r/il/8cb151/2923651420/il_794xN.2923651420_ldim.jpg", user_id=3 )
    plant8 = Plant(name= "Shampoo Ginger Rhizomes, Zingiber zerumbet, Pine Cone Ginger Plant, Free Shipping w/ Free Offer", price= 12.00, details= "2, 4 or 8 rhizomes of shampoo ginger. Dug fresh for every order. Can be consumed or planted for the flowers. Free shipping include, Free offer, Purchase 2 separate orders and receive a 3rd order of the same for free.", preview_image_url= "https://i.etsystatic.com/9060073/r/il/96a911/4279828642/il_794xN.4279828642_8ycq.jpg", user_id=3 )
    plant9 = Plant(name= "Angelwing Begonia |Begonia Maculata| | Begonia Wightii | pot", price= 14.40, details= "Water: Keep the soil generally moist, letting the top half inch of soil dry out between watering. Will not tolerate soggy soil. Light: Bright, indirect light. Higher light levels will promote strong growth and blooms, but avoid direct sunlight.Temperature & Humidity: 65F (18C) and 86F (30C). High humidity is important. >45C deally. A digital hygrometer can be useful to monitor humidity.", preview_image_url= 'https://i.etsystatic.com/23131452/r/il/826a92/3067634088/il_794xN.3067634088_f09m.jpg', user_id=1 )
    plant10 = Plant(name= "Rare Tradescantia Nanouk Lilac Plant | Rare Tradescantia Pot | Rare Pink Wandering Jew | Easy care hardy indoor houseplant in a nursery pot", price= 12.59, details= "Rare Tradescantia Nanouk Lilac Plant in a nursery pot. This plant has a beautiful pink and green variation. What you get: A similar plant as the images as per the selection you make in the variations in a Nursery pot.", preview_image_url= "https://i.etsystatic.com/23378564/r/il/5a0366/2393912328/il_794xN.2393912328_4sdb.jpg", user_id=3 )
    plant11 = Plant(name= "Tillandsia Cyanea - Unique and Rare Air Plant - 30 Day Air Plant Guarantee - FAST SHIPPING", price= 5.99, details= "Tillandsia Cyanea is a unique and rare air plant species that is native to South America. It has long, curly leaves and produces delicate purple and pink blooms. It is perfect for hanging terrariums and makes a great conversation piece.", preview_image_url='https://images.squarespace-cdn.com/content/v1/5806a87f6a4963c2ddce112c/1595941786653-172TO8WW2FCRKP4HP7L8/Cool+Plant+Pots+Inspiration.jpg', user_id=1)
    plant12 = Plant(name= "Xerographica Air Plants - Large and Striking - 30 Day Air Plant Guarantee - FAST SHIPPING", price= 14.95, details= "Xerographica is a stunning air plant species that is known for its large size and striking appearance. It has long, delicate leaves that can grow up to 2 feet in length. This plant is perfect for larger terrariums, glass globes, and air plant displays.", preview_image_url='https://media1.popsugar-assets.com/files/thumbor/Ftz9nsW7Kr0CpFnoImCPmLbl8qE/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2020/06/10/072/n/1922794/912f8c332e66da6a_netimgSx5bat/i/Tal-Bert-Lepidolite-Mini-Planter.jpg', user_id=2)
    plant13 = Plant(name= "3 Pack of Caput Medusae Grass - Dangerous to Grow - 30 Day Air Plant Guarantee - FAST SHIPPING", price= 4.95, details= "Caput Medusae is a hardy and easy to grow air plant species that is native to Central and South America. It has long, curly leaves that grow out from a central rosette. This plant is perfect for air plant displays and is great for beginners.", preview_image_url='https://i.pinimg.com/736x/c2/bf/2b/c2bf2b4d15ad1ae09263316415b77f61.jpg', user_id=3)
    plant14 = Plant(name= "2 Pack of Butzii Flowers  - Messy to Grow - 30 Day Air Plant Guarantee - FAST SHIPPING", price= 9.95, details= "Butzii is a hardy and adaptable air plant species that is native to Central and South America. It has short, stubby leaves that grow out from a central rosette. This plant is perfect for air plant displays and is great for beginners.", preview_image_url='https://pbs.twimg.com/media/E90QF2QVgAQjALM?format=jpg&name=large', user_id=1)
    plant15 = Plant(name= "4 Pack of Brachycaulos Dollar Tree - Fast to Grow - 30 Day Air Plant Guarantee - FAST SHIPPING", price= 7.95, details= "Brachycaulos is a hardy and easy to grow air plant species that is native to Central and South America. It has thick, stubby leaves that grow out from a central rosette. This plant is perfect for air plant displays and is great for beginners.", preview_image_url='https://3dprint.com/wp-content/uploads/2016/01/3dp_ten3dpthings_happypots.jpg', user_id=2)
    plant16 = Plant(name= "2 Pack of Fuchsii Kite Plant - Lame - 30 Day Air Plant Guarantee - MEH SHIPPING", price= 9.95, details= "Fuchsii is a hardy and versatile air plant species that is native to Central and South America. It has long, delicate leaves that grow out from a central rosette. This plant is perfect for air plant displays and is great for both beginners and experienced air plant enthusiasts.", preview_image_url='http://cdn.home-designing.com/wp-content/uploads/2015/10/funny-easter-island-head-planter-600x921.jpg', user_id=3)
    plant17 = Plant(name= "Tectorum Onion Plant - Adaptable - 30 Day Air Plant Guarantee - BAD SHIPPING", price= 9.95, details= "Tectorum is a hardy and adaptable air plant species that is native to Central and South America. It has long, wavy leaves that grow out from a central rosette. This plant is perfect for air plant displays and is great for both beginners and experienced air plant enthusiasts.", preview_image_url='https://cdn.homedit.com/wp-content/uploads/2011/08/Unique-Indoor-Garden-Gift-Ideas-Terracota-Plant-Pot-Design-by-Namiko-Murakoshi-Hairy-Babes.jpg', user_id=1)
    plant18 = Plant(name= "12 Pack of Greenie Mushroom | Hardy and Low Maintenance | Some Day Shipping Guarantee | SLOW SHIPPING", price= 5.99, details= "Stricta is a hardy and low maintenance air plant species that is native to Central and South America. It has long, slender leaves that grow out from a central rosette. This plant is perfect for air plant displays and is great for those who are new to air plant care.", preview_image_url='https://i.cbc.ca/1.3965962.1486147955!/fileImage/httpImage/image.jpg_gen/derivatives/original_780/roz-planter.jpg', user_id=2)
    plant19 = Plant(name= "Fresh Succulents - FROM FARMER - FAST SHIPPING", price= 14.95, details= "Xerographica is a unique and striking air plant species that is native to Central and South America. It has long, curled leaves that grow out from a central rosette. This plant is perfect for air plant displays and is great for experienced air plant enthusiasts.", preview_image_url='https://cdn.shopify.com/s/files/1/0040/2679/4054/files/Whale_Planter_Vase_for_Plants_and_Succulents_by_Meow3DStore_large.jpg?v=1586372982', user_id=3)
    plant20 = Plant(name= "RANDOM PLANT - Possibly Illegal - 2 WEEK Gurantee - FAST SHIPPING", price= 7.95, details= "Ionantha is a hardy and easy to grow air plant species that is native to Central and South America. It has long, slender leaves that grow out from a central rosette. This plant is perfect for air plant displays and is great for beginners.", preview_image_url='https://empire-s3-production.bobvila.com/slides/42075/vertical_slide_wide/concrete-planter-ideas.jpg?1618927212', user_id=1)

    all_plants = [plant1, plant2, plant3, plant4, plant5, plant6, plant7, plant8, plant9, plant10, plant11, plant12, plant13, plant14, plant15, plant16, plant17, plant18, plant19, plant20 ]
    add_plant = [db.session.add(plant) for plant in all_plants]
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_plants():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.plants RESTART IDENTITY CASCADE;")
    else:
        db.session.execute("DELETE FROM plants")

    db.session.commit()
